## Numpy 기초연습문제

------

In [1]:
# numpy 패키지는 보통 np로 축약한다.
import numpy as np

### 1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.


In [2]:
# 0으로 채워진 3X4 행렬 생성
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
# 3행
a.shape[0]

3

In [4]:
# 4열
a.shape[1]

4

### 2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.


In [5]:
# 이중 for문을 통해 채워 넣는다.
num = 1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i,j] = num
        num += 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

### 3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오.

In [6]:
# 행렬에서의 인덱싱 (7을 꺼내기)
a[1,2]

7.0

### 4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다.


In [7]:
a.shape

(3, 4)

In [8]:
# 차원을 유지하는 경우
a[[1],:]

array([[5., 6., 7., 8.]])

In [9]:
# bracket이 하나
a[1,:]

array([5., 6., 7., 8.])

### 5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.


In [10]:
# 둘째 열과 셋쨰 열 가져오기
a[:, [1,2]]

array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.]])

### 6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리안 인덱싱을 하시오.

In [11]:
# a에서 6보다 작거나 같은 값 나오도록 하기
a[a <= 6]

array([1., 2., 3., 4., 5., 6.])

### 7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.


In [12]:
# 3X4 행렬을 0에서 1 사이의 난수로 채우기
b = np.random.random((3,4))
b

array([[0.81615656, 0.16068232, 0.52287877, 0.98583149],
       [0.90394339, 0.93799277, 0.66675386, 0.1950704 ],
       [0.20757454, 0.28971925, 0.60608208, 0.34815667]])

### 8. a와 b의 요소곱을 하여 c에 저장하시오.


In [13]:
# 행렬곱이 아니고 같은 위치에 존재하는 스칼라끼리의 곱
c = a * b
c

array([[0.81615656, 0.32136465, 1.56863632, 3.94332596],
       [4.51971695, 5.62795664, 4.66727701, 1.56056323],
       [1.86817086, 2.89719253, 6.66690288, 4.1778801 ]])

### 9. b의 전치행렬을 구하여 d에 저장하시오.


In [14]:
# 전치행렬
d = b.T
d

array([[0.81615656, 0.90394339, 0.20757454],
       [0.16068232, 0.93799277, 0.28971925],
       [0.52287877, 0.66675386, 0.60608208],
       [0.98583149, 0.1950704 , 0.34815667]])

In [15]:
# 3X4  -> 4X3
d.shape

(4, 3)

### 10. a와 d에 대하여 각 차원의 크기를 출력하시오.


In [16]:
# 각 차원의 크기 출력
print(a.shape, d.shape)

(3, 4) (4, 3)


### 11. a와 d의 행렬곱을 계산하여 e에 저장하시오.


In [17]:
# a와 d의 행렬곱
e = a.dot(d)
e

array([[ 6.64948349,  5.56047212,  3.99788598],
       [16.59168009, 16.37551382,  9.80401617],
       [26.53387669, 27.19055552, 15.61014636]])

### 12. e에 대하여 각 열의 합을 계산하시오.

In [18]:
# 각 열의 합 계산
np.sum(e, axis=0)

array([49.77504028, 49.12654146, 29.41204852])